### PR TITLE
Recover from WebSocket failures with backoff

### LINKED ISSUE #60: Recover from WebSocket read failures
This panic took Rocket down recently. We should try and recover from errors like this.

```
rocket_1    | panic: repeated read on failed websocket connection
rocket_1    |
rocket_1    | goroutine 31 [running]:
rocket_1    | github.com/ubclaunchpad/rocket/vendor/github.com/gorilla/websocket.(*Conn).NextReader(0xc42013c280, 0xc4201692b8, 0x0, 0x0, 0xc420032ec0, 0xc420032ec0)
rocket_1    | 	/go/src/github.com/ubclaunchpad/rocket/vendor/github.com/gorilla/websocket/conn.go:959 +0x3d9
rocket_1    | github.com/ubclaunchpad/rocket/vendor/github.com/gorilla/websocket.(*Conn).ReadJSON(0xc42013c280, 0x8bbdc0, 0xc420180ee0, 0xbf0600, 0xc224e0)
rocket_1    | 	/go/src/github.com/ubclaunchpad/rocket/vendor/github.com/gorilla/websocket/json.go:50 +0x2f
rocket_1    | github.com/ubclaunchpad/rocket/vendor/github.com/nlopes/slack.(*RTM).receiveIncomingEvent(0xc420171e00)
rocket_1    | 	/go/src/github.com/ubclaunchpad/rocket/vendor/github.com/nlopes/slack/websocket_managed_conn.go:288 +0xaa
rocket_1    | github.com/ubclaunchpad/rocket/vendor/github.com/nlopes/slack.(*RTM).handleIncomingEvents(0xc420171e00, 0xc4205b4a80)
rocket_1    | 	/go/src/github.com/ubclaunchpad/rocket/vendor/github.com/nlopes/slack/websocket_managed_conn.go:223 +0x2d
rocket_1    | created by github.com/ubclaunchpad/rocket/vendor/github.com/nlopes/slack.(*RTM).ManageConnection
rocket_1    | 	/go/src/github.com/ubclaunchpad/rocket/vendor/github.com/nlopes/slack/websocket_managed_conn.go:54 +0x265
```

### PR DESCRIPTION
**Pull request by bfbachmann**
Fixes #60 

I've just updated our Slack dependency, so hopefully that fixes the issue. It seems they've improved their error handling in reading from the WebSocket. If the same error crops up again I'll have to resort to some form of the `recover` solution I has before.

### CODE REVIEW

File: bot/bot.go [hunk 1]
```diff
@@ -94,6 +95,26 @@ func (b *Bot) Start() {
...
+			defer func() {
+				if r := recover(); r != nil {
+					b.log.Info("Recovered from panic in manageConnection")
+				}
+			}()
+			b.rtm.ManageConnection()
+		}()
+		if time.Since(start) < time.Second*3 {
+			// The connection is failing quite quickly. Let's back off.
+			time.Sleep(10)
```
Comment (bfbachmann) [inline bot/bot.go]: Should probably fail after a few consecutive retires.

Comment (bfbachmann) [reply bot/bot.go]: This is also wrong, `time.Sleep` takes `time.Duration` as an argument, not an `int`.

File: bot/bot.go [hunk 2]
```diff
@@ -94,6 +95,33 @@ func (b *Bot) Start() {
 	}
 }
 
+// Manages a Slack WebSocket connection and re-establishes the connection
+// when errors occur.
+func (b *Bot) manageConnection() {
```
Comment (jordanschalm) [inline bot/bot.go]: return error
